import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    setupFiles: ['__tests__/setup.ts'],
    pool: 'forks',
    poolOptions: {
      forks: { singleFork: true },
    },
    include: ['__tests__/**/*.test.ts', '__tests__/**/*.test.tsx'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      reportsDirectory: './coverage',
      include: [
        'ai/**/*.ts',
        'services/**/*.ts',
        'stores/**/*.ts',
      ],
      exclude: [
        'node_modules/**',
        '**/*.test.ts',
        '**/*.test.tsx',
        '**/__tests__/**',
        '**/types.ts',
        'ai/SecurityScanner.ts',
        'ai/PerformanceOptimizer.ts',
        'ai/TestGenerator.ts',
        'ai/CommandRegistry.ts',
        'services/MCPPrompts.ts',
        'services/DataExporter.ts',
        'services/DataImporter.ts',
        'services/SentryService.ts',
        'services/ErrorReportingService.ts',
        'services/StorageCleanup.ts',
        'services/StorageMonitor.ts',
        'services/VersioningService.ts',
        'services/CloudSyncService.ts',
        'services/AIAgentWorkflow.ts',
        'services/MCPResources.ts',
        'services/MCPClient.ts',
        'services/SnapshotService.ts',
        'stores/index.ts',
        'stores/optimizedHooks.ts',
        'stores/selectors.ts',
        'stores/useFileStoreZustand.ts',
        'stores/useFloatingPanelStore.ts',
        'stores/useIPCStore.ts',
        'stores/useModelStoreZustand.ts',
        'stores/usePanelPinStore.ts',
        'stores/usePanelTabGroupStore.ts',
        'stores/usePreviewHistoryStore.ts',
        'stores/usePreviewStore.ts',
        'stores/useProxyStoreZustand.ts',
        'stores/useQuickActionsStore.ts',
        'stores/useSessionStore.ts',
        'stores/useSettingsStore.ts',
        'stores/useWindowStore.ts',
      ],
    },
  },
})
