/**
 * file injector.ts
 * description 主题样式注入与切换工具 — 生成 CSS 变量、Tailwind 配置、globals.css 片段
 * module @yyc3/cli/themes
 * author YanYuCloudCube Team <admin@0379.email>
 * version 1.0.0
 * created 2026-06-20
 * status active
 *
 * brief 提供主题注入所需的各类资源生成：
 *   - CSS 变量字符串（含暗色模式）
 *   - Tailwind 配置片段
 *   - globals.css 片段
 *   - next.config 主题切换脚本
 *
 * copyright YanYuCloudCube Team
 * license MIT
 */

import type { ThemeConfig } from "./registry"

/**
 * 生成 CSS 变量字符串（含 :root 与 .dark 双模式）
 */
export function generateThemeCssVars(theme: ThemeConfig): string {
  const lines: string[] = []

  // 亮色模式（或默认）
  lines.push(`:root[data-theme="${theme.name}"] {`)
  lines.push(`  --primary: ${theme.primaryColor};`)
  lines.push(`  --background: ${theme.backgroundColor};`)
  if (theme.accentColor) {
    lines.push(`  --accent: ${theme.accentColor};`)
  }
  if (theme.cssVars) {
    for (const [key, value] of Object.entries(theme.cssVars)) {
      lines.push(`  ${key}: ${value};`)
    }
  }
  lines.push(`  --radius: ${radiusToCss(theme.radius)};`)
  lines.push("}")
  lines.push("")

  // 暗色模式（如果是亮色主题，则提供暗色变体）
  if (!theme.darkMode) {
    lines.push(`.dark[data-theme="${theme.name}"] {`)
    lines.push(`  --primary: ${darkenColor(theme.primaryColor)};`)
    lines.push(`  --background: ${darkenColor(theme.backgroundColor)};`)
    if (theme.accentColor) {
      lines.push(`  --accent: ${darkenColor(theme.accentColor)};`)
    }
    lines.push("}")
  }

  return lines.join("\n")
}

/**
 * 生成 Tailwind 配置片段
 */
export function generateTailwindConfig(theme: ThemeConfig): string {
  const colors: Record<string, string> = {
    primary: "var(--primary)",
    background: "var(--background)",
    accent: "var(--accent)",
  }

  if (theme.accentColor === undefined) {
    delete colors.accent
  }

  // 注入额外 CSS 变量作为颜色
  if (theme.cssVars) {
    for (const key of Object.keys(theme.cssVars)) {
      // --cyber-glow -> cyber-glow
      const colorKey = key.replace(/^--/, "")
      colors[colorKey] = `var(${key})`
    }
  }

  const config = {
    theme: {
      extend: {
        colors,
        borderRadius: {
          lg: "var(--radius)",
          md: "calc(var(--radius) - 2px)",
          sm: "calc(var(--radius) - 4px)",
        },
        fontFamily: theme.font
          ? {
            sans: [`var(--font-${theme.font})`, "sans-serif"],
          }
          : undefined,
      },
    },
  }

  return `// Auto-generated by yyc3 themes — ${theme.name}
export const themeConfig = ${JSON.stringify(config, null, 2)}
`
}

/**
 * 生成 globals.css 片段（含 @layer base）
 */
export function generateGlobalsCss(theme: ThemeConfig): string {
  const lines: string[] = []

  lines.push(`/* YYC³ Theme: ${theme.name} — ${theme.label} */`)
  lines.push(`/* ${theme.description} */`)
  lines.push("")

  // @layer base 主题变量
  lines.push("@layer base {")
  lines.push(`  :root[data-theme="${theme.name}"] {`)
  lines.push(`    --primary: ${theme.primaryColor};`)
  lines.push(`    --background: ${theme.backgroundColor};`)
  if (theme.accentColor) {
    lines.push(`    --accent: ${theme.accentColor};`)
  }
  if (theme.cssVars) {
    for (const [key, value] of Object.entries(theme.cssVars)) {
      lines.push(`    ${key}: ${value};`)
    }
  }
  lines.push(`    --radius: ${radiusToCss(theme.radius)};`)
  lines.push("  }")
  lines.push("")

  // body 应用
  lines.push(`  [data-theme="${theme.name}"] body {`)
  lines.push("    background-color: var(--background);")
  lines.push("    color: var(--foreground, currentColor);")
  lines.push("  }")
  lines.push("}")

  return lines.join("\n")
}

/**
 * 生成主题切换脚本（前端运行时）
 */
export function generateThemeSwitcherScript(): string {
  return `
// YYC³ Theme Switcher — Auto-generated
(function() {
  const STORAGE_KEY = 'yyc3-theme'
  const DEFAULT_THEME = 'yyc3-brand'

  function applyTheme(name) {
    document.documentElement.setAttribute('data-theme', name)
    try { localStorage.setItem(STORAGE_KEY, name) } catch (e) {}
  }

  function getCurrentTheme() {
    try { return localStorage.getItem(STORAGE_KEY) || DEFAULT_THEME } catch (e) {
      return DEFAULT_THEME
    }
  }

  function toggleDark() {
    const current = document.documentElement.getAttribute('data-theme')
    const isDark = document.documentElement.classList.contains('dark')
    if (isDark) {
      document.documentElement.classList.remove('dark')
    } else {
      document.documentElement.classList.add('dark')
    }
  }

  // Auto-apply on load
  const initial = getCurrentTheme()
  applyTheme(initial)

  // Export
  window.YYC3Theme = {
    apply: applyTheme,
    get: getCurrentTheme,
    toggleDark: toggleDark,
  }
})()
`.trim()
}

/**
 * 生成主题切换 React Hook
 */
export function generateThemeHook(): string {
  return `
import { useState, useEffect, useCallback } from 'react'

const STORAGE_KEY = 'yyc3-theme'
const DEFAULT_THEME = 'yyc3-brand'

export function useYYC3Theme() {
  const [theme, setThemeState] = useState<string>(DEFAULT_THEME)
  const [isDark, setIsDark] = useState<boolean>(false)

  useEffect(() => {
    const saved = typeof window !== 'undefined'
      ? localStorage.getItem(STORAGE_KEY) || DEFAULT_THEME
      : DEFAULT_THEME
    setThemeState(saved)
  }, [])

  const setTheme = useCallback((name: string) => {
    setThemeState(name)
    if (typeof document !== 'undefined') {
      document.documentElement.setAttribute('data-theme', name)
    }
    if (typeof window !== 'undefined') {
      try { localStorage.setItem(STORAGE_KEY, name) } catch (e) {}
    }
  }, [])

  const toggleDark = useCallback(() => {
    setIsDark((prev) => {
      const next = !prev
      if (typeof document !== 'undefined') {
        if (next) document.documentElement.classList.add('dark')
        else document.documentElement.classList.remove('dark')
      }
      return next
    })
  }, [])

  return { theme, setTheme, isDark, toggleDark }
}
`.trim()
}

// ============================================================================
// 内部工具函数
// ============================================================================

function radiusToCss(radius?: ThemeConfig["radius"]): string {
  const map: Record<NonNullable<ThemeConfig["radius"]>, string> = {
    none: "0px",
    sm: "0.25rem",
    default: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
  }
  return radius ? map[radius] : "0.5rem"
}

/**
 * 简单的颜色变暗算法（仅用于亮色主题的暗色变体生成）
 * 不处理 oklch() 等复杂值，遇到则原样返回
 */
function darkenColor(color: string): string {
  // oklch / hsl / rgb / rgba 等复杂值直接返回
  if (color.startsWith("oklch") || color.startsWith("hsl") || color.startsWith("rgb")) {
    return color
  }
  // radial-gradient / linear-gradient 等直接返回
  if (color.includes("gradient")) {
    return color
  }
  // transparent 直接返回
  if (color === "transparent") {
    return color
  }
  // hex 颜色简单变暗
  if (color.startsWith("#") && color.length === 7) {
    try {
      const r = Math.floor(parseInt(color.slice(1, 3), 16) * 0.8)
      const g = Math.floor(parseInt(color.slice(3, 5), 16) * 0.8)
      const b = Math.floor(parseInt(color.slice(5, 7), 16) * 0.8)
      return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`
    } catch {
      return color
    }
  }
  return color
}
