import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    core: 'src/core/index.ts',
    components: 'src/components/index.ts',
    business: 'src/components/business/index.ts',
    'business/ai': 'src/components/business/ai/index.ts',
    'business/enterprise': 'src/components/business/enterprise/index.ts',
    'business/data': 'src/components/business/data/index.ts',
    'business/system': 'src/components/business/system/index.ts',
    'business/platform': 'src/components/business/platform/index.ts',
    'business/charts': 'src/components/business/charts/index.ts',
    'business/security': 'src/components/business/security/index.ts',
    'business/pwa': 'src/components/business/pwa/index.ts',
    'business/enhanced': 'src/components/business/enhanced/index.ts',
    'business/dialogs': 'src/components/business/dialogs/index.ts',
    themes: 'src/themes/index.ts',
    shadcn: 'src/shadcn.ts',
  },
  format: ['esm'],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  external: ['react', 'react-dom', '@yyc3/core'],
  treeshake: true,
  minify: false,
})
